### ISSUE TITLE
Correcties in github_tutorial.md

### ISSUE THREAD

**Issue by melsk-r** [VNG-Realisatie/Tutorial#6]
In github_tutorial.md wordt in de uitleg van de term branch de opmerking 

> In Git worden branches dus op een andere manier gebruikt dan in SVN

geplaatst. Dit klopt echter niet. Ook in SVN kan het de bedoeling zijn een branch weer te mergen met de trunk. Dat we dit niet doen i.h.k.v. de Nieuwe aanpak heeft zo zijn reden.

Ook wil ik een aantal andere kleine tekstuele correcties aanbrengen.

**Comment by fsamwel** [comment]
Opgelost door pull request #7 (die inmiddels is gemerged)
